name: wstore
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  cloud_firestore:
  firebase_core: 
  firebase_auth: 
  random_string: ^2.3.1
  shared_preferences:
  image_picker: 
  firebase_storage:
  flutter_stripe:
  http:  
  url_launcher: ^6.1.7
  fl_chart: ^0.66.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.5
  get_storage: ^2.1.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
